### ISSUE TITLE
bipolar and RGC funtions

### ISSUE THREAD

**Issue by TayebehY** [isetbio/EJLPhosphene#2]
Hi 

The problem I encounter repeatedly when working with the ISETBio software is that the bipolar and RGC function does not exist which I think is related to the previous version and has been substituted with the class version (bipolarLayer). However, many functions are still based on the previous version. 
I would appreciate it if the previous code can also be added to the repository.

**Comment by jamesgolden1** [comment]
Hi TayebehY, you can access the appropriate version of Isetbio that works with RGC-Reconstruction by switching to the 'phosphenePaper' [branch of isetbio](https://github.com/isetbio/isetbio/tree/phosphenePaper). This should be compatible with the master branches of RGC-Reconstruction and EJLPhosphene repositories.

**Comment by TayebehY** [comment]
Thank you so much. I really appreciate your help.
