### ISSUE TITLE
Problem in computeBipolar under primaArray class

### ISSUE THREAD

**Issue by TayebehY** [isetbio/EJLPhosphene#4]
Hi 

Actually, as I was trying to go through the codes and the command primaArray.compute cause an error. When I tried to find the reason I figured out that in this function the computeBipolar code can not be executed. 

Under computeBibolar when I tried to see where the problem is I found out that the following commands can not be executed. based on the matrix dimensions I have changed the .* to * (in XW2RGBFormat(cmat.*RGB2XWFormat(bpResponseCenterFull)) and it worked. 

bpResponseCenterFullNoisy = XW2RGBFormat(cmat.*RGB2XWFormat(bpResponseCenterFull),size(bpResponseCenterFull,1)+blurSize-1,size(bpResponseCenterFull,2)+blurSize-1);

bpResponseSurroundFullNoisy = XW2RGBFormat(cmat.*RGB2XWFormat(bpResponseSurroundFull),size(bpResponseSurroundFull,1)+blurSize-1,size(bpResponseSurroundFull,2)+blurSize-1);
 

I would appreciate it if you let me know if my understanding is accurate and I can make this change.

**Comment by jamesgolden1** [comment]
Hi TayebehY, can you supply the error, and confirm that the file name is computeBipolar.m? A possible alternative is compute.m in @bipolarMosaic.

You are in the 'phosphenePaper' branch of isetbio, correct? It should be commit 99b0de0d if you check 'git reflog' (q to escape).

**Comment by TayebehY** [comment]
Hi James
Thank you for your response. Actually, I am talking about the computeBipolar.m in @primaArray. Exactly in the EJLPhosphene folder not directly in ISETBio. 

This is the error I get when I execute the command:    primaRecon.compute(movieIn)

Error using  .* 
Matrix dimensions must agree.

Error in primaArray/computeBipolar (line 243)
bpResponseCenterFullNoisy =
XW2RGBFormat(cmat.*RGB2XWFormat(bpResponseCenterFull),size(bpResponseCenterFull,1)+blurSize-1,size(bpResponseCenterFull,2)+blurSize-1);

Error in primaArray/compute (line 40)
primaArray.computeBipolar(cMosaicNS)

**Comment by jamesgolden1** [comment]
You’re in the master branch right? I noticed the repository had the default
set to something else incorrectly.

**Comment by TayebehY** [comment]
Yes. Actually executing the lines one by one I can see than cmat and RGB2XWFormat(bpResponseCenterFull) have totally different dimensions but it was like m*n and n*k so it is working when I change it to XW2RGBFormat(cmat*RGB2XWFormat(bpResponseCenterFull)

**Comment by jamesgolden1** [comment]
Hi TayebehY, you are in the master branch of EJLPhosphene, correct?

I believe you need to use the line as it originally is, which is just the * command for multiplication, not .* .

What are you using as input? I believe they need to be 100x100x24 movies. (The number of frames can change but has to be greater than 24).

**Comment by TayebehY** [comment]
Yes, you are right. Thank you so much.
