### ISSUE TITLE
Question about movie input for the primaArray object

### ISSUE THREAD

**Issue by TayebehY** [isetbio/EJLPhosphene#5]
Hi 

I would really appreciate it if you also answer my question about the movie input for the primaArray object. I was wondering if it is possible to use a static image instead of a movieInput. If not, is it possible for me to generate my own movieInput?

I really appreciate your help and thank you so much in advance.

**Comment by jamesgolden1** [comment]
Yes, but due to the temporal aspect of the model response you should make
the input a movie of 40 frames where each frame is the image of interest.

**Comment by TayebehY** [comment]
Thank you so much for your help.
