### ISSUE TITLE
Hardware implementation

### ISSUE THREAD

**Issue by TayebehY** [isetbio/EJLPhosphene#7]
Hi 

I am working on the hardware implementation to define the electrical stimulation based on the ISETBio tool. I would appreciate it if you let me know if there is any similar work from your group. I am worried that the system is too complicated to be implemented on hardware. 

Thank you so much.

**Comment by jamesgolden1** [comment]
I don't think there has been work in this direction directly integrated
with Isetbio.

Could you specify what you mean by hardware? Some sort of simulation like
on an FPGA?

Or are you implementing your own version of electrical stimulation in
Matlab/Isetbio?

James

**Comment by TayebehY** [comment]
Thank you so much for your response. 
Actually, I mean implementing the network on hardware like FPGA. I am mainly planning to implement something like a healthy retina on hardware.

Also, I would really appreciate it if you let me know if the healthy retina has the structure of a neural network or convolutional neural network. I suspect it has but It is difficult for me to extract the weights to build my own neural network to then implement it on hardware.

**Comment by jamesgolden1** [comment]
(Again apologies for the very slow reply!)

You ask a very interesting question about the retina, and there is a lot of
work in that area. Here are some good places to start:

https://med.stanford.edu/chichilnisky/publications.html

Field GD & Chichilnisky EJ (2007) Information processing in the primate
retina: circuitry and coding.
<http://www.ncbi.nlm.nih.gov/pubmed/17335403> *Annual
Review of Neuroscience* 30:1-30. [reprint]
<https://med.stanford.edu/content/dam/sm/chichilnisky/documents/publications/Field2007a.pdf>

Kling A, Field GD, Brainard DH, Chichilnisky EJ (2019). Probing computation
in the primate visual system at single-cone resolution.
<https://www.ncbi.nlm.nih.gov/pubmed/30857477> *Annu Rev Neurosci.*
 42:169–86. [reprint]
<https://med.stanford.edu/content/dam/sm/chichilnisky/documents/publications/Kling2019.pdf>

This is a new Stanford course that has some great overviews (but doesn't
include some of the Chichilnisky lab's latest results).

https://github.com/slinderman/stats320 (lectures 8 and 9 as well as lab 5):
Encoding models of retinal ganglion cells
<https://github.com/slinderman/stats320/blob/main/lectures/lecture08.pdf>
Encoding models of retinal ganglion cells II
<https://github.com/slinderman/stats320/blob/main/lectures/lecture09.pdf>
Deep encoding models of retinal spike trains
<https://colab.research.google.com/github/slinderman/stats320/blob/main/labs/Lab_5_Encoding_models_of_retinal_ganglion_cells.ipynb>
Here are those latest papers in this area:
Batty E, Merel J, Brackbill N, Heitman A, Sher A, Litke A, Chichilnisky EJ,
Paninski L (2017). Multilayer recurrent network models of primate retinal
ganglion cell responses. <https://openreview.net/forum?id=HkEI22jeg>
*International
Conference on Learning Representations*, Toulon, France. [reprint]
<https://med.stanford.edu/content/dam/sm/chichilnisky/documents/publications/Batty2017.pdf>

Brackbill N, Rhoades C, Kling A, Shah NP, Sher A, Litke AM, Chichilnisky EJ
(2020). Reconstruction of natural images from responses of primate retinal
ganglion cells. <https://pubmed.ncbi.nlm.nih.gov/33146609/> *eLife *
2020;9:e58516. [reprint]
<https://med.stanford.edu/content/dam/sm/chichilnisky/documents/publications/Brackbill2021.pdf>

As for an in silico simulation of the retina, the Boahen lab at Stanford is
a good place to start:
https://web.stanford.edu/group/brainsinsilicon/

James

**Comment by TayebehY** [comment]
Thank you so much for your detailed response. I really really appreciate it. 

Best
